name: Docker

on:
  push:
    paths-ignore:
      - .gitignore
      - LICENSE
      - '**.md'
    branches:
      - master
      - dev

  release:
    types:
      - published

env:
  DOCKER_BASE_NAME: slashnephy/epgbird

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare image tag (master)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV
      - name: Prepare image tag (dev)
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: echo "DOCKER_TAG=dev" >> $GITHUB_ENV
      - name: Prepare image tag (Release)
        if: github.event_name == 'release'
        run: echo "DOCKER_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_BASE_NAME }}:${{ env.DOCKER_TAG }}
